### PR TITLE
fix: afterTurn compaction sweep and ownsCompaction bypass

### LINKED ISSUE #15: CRITICAL: compact() never compacts — ownsCompaction:true but runtime params mismatch
### Summary

When the Graphiti plugin is assigned to the `contextEngine` slot (`plugins.slots.contextEngine: "graphiti"`), **session compaction never runs**. Sessions grow unbounded until they hit the context limit, at which point `/compact` reports:

```
⚙️ Compaction skipped: no-messages • Context 199k/200k (99%)
```

This is a **critical bug** — it makes long-lived sessions unusable on any installation using the Graphiti context engine.

### Root Cause

The plugin declares `ownsCompaction: true` in its `ContextEngineInfo`:

```typescript
// context-engine.ts:81
readonly info: ContextEngineInfo = {
  id: "graphiti",
  name: "Graphiti Knowledge Graph",
  version: PLUGIN_VERSION,
  ownsCompaction: true,  // ← tells OpenClaw: "I handle compaction"
};
```

When OpenClaw's runtime triggers compaction (either auto or manual via `/compact`), it delegates to `contextEngine.compact()`. But the plugin's `compact()` method expects specific params that the runtime doesn't provide:

```typescript
// context-engine.ts:231-271
async compact(params: {
  sessionId: string;
  sessionFile?: string;
  tokenBudget?: number;
  force?: boolean;
  messages?: unknown[];          // ← expects this
  legacyParams?: { bridge?: { compact: () => Promise<any> } };  // ← or this
}): Promise<CompactResult> {
  try {
    if (params.messages) {       // ← runtime doesn't pass messages
      // ... ingest to graph, return compacted: true
    }

    if (params.legacyParams?.bridge) {  // ← runtime doesn't pass bridge
      // ... legacy fallback, return compacted: true
    }

    // FALLS THROUGH — always returns false
    return { ok: true, compacted: false, reason: "no-messages" };
  }
}
```

The OpenClaw runtime calls `compact()` with `runtimeContext`, `tokenBudget`, `force`, `compactionTarget`, etc. — but NOT `messages` or `legacyParams.bridge`. So the plugin:

1. Checks `params.messages` → undefined → skip
2. Checks `params.legacyParams?.bridge` → undefined → skip
3. Returns `{ compacted: false, reason: "no-messages" }`

Since `ownsCompaction: true`, the runtime trusts this result and does NOT fall back to built-in compaction. The session never compacts.

### Evidence from production

Session `#shiba-dev` (Discord channel):
- **3.7MB transcript** — 455 messages (38 user, 202 assistant, 215 tool results)
- **190k/200k tokens** (95% full) → eventually hit 199k/200k (99%)
- **0 compactions** in the session's entire lifetime (`memoryFlushCompactionCount: 0`)
- Manual `/compact` returns: `Compaction skipped: no-messages`
- Context reset triggered: `Context limit exceeded. I've reset our conversation to start fresh`

### Impact

- **All sessions using the Graphiti context engine** cannot compact
- Sessions grow until context limit → forced reset → loss of conversation context
- The longer a session runs, the more likely it is to hit this
- Particularly affects sessions with heavy tool usage (sub-agents, PR reviews, etc.)

### Proposed Fix

The `compact()` method needs to handle the case where the runtime doesn't pass `messages` directly. Two options:

**Option A: Read messages from session file (preferred)**
```typescript
async compact(params) {
  let messages = params.messages;

  // If runtime didn't pass messages, read from session file
  if (!messages && params.sessionFile) {
    messages = await readMessagesFromSessionFile(params.sessionFile);
  }

  if (messages && messages.length > 0) {
    // ... existing ingest logic
    return { ok: true, compacted: true };
  }

  // If we still have no messages AND there's a legacy bridge, use it
  if (params.legacyParams?.bridge) {
    await params.legacyParams.bridge.compact();
    return { ok: true, compacted: true };
  }

  // Last resort: signal compacted=true to let the runtime do its built-in truncation
  // The graph already holds knowledge from prior ingestion (afterTurn)
  return { ok: true, compacted: true };
}
```

**Option B: Don't claim ownership**

Set `ownsCompaction: false` so OpenClaw uses its built-in compaction. The plugin still captures conversations via `before_compaction` hook and `afterTurn`. This is the safe/simple fix while Option A is developed.

```typescript
readonly info: ContextEngineInfo = {
  ownsCompaction: false,  // ← let OpenClaw handle compaction
};
```

### Workaround

Until fixed, users can work around this by either:

1. **Removing the contextEngine slot** from config:
   ```json
   { "plugins": { "slots": { "contextEngine": null } } }
   ```
   This falls back to OpenClaw's built-in `legacy` context engine for compaction.

2. **Manually `/reset` sessions** when they get large — but this loses conversation context.

### Environment

- OpenClaw: v2026.3.8
- Plugin: `@robertogongora/graphiti` v0.6.1
- Model: claude-opus-4-6 (200k context window)
- Config: `plugins.slots.contextEngine: "graphiti"`, `compaction.mode: "safeguard"`

### PR DESCRIPTION
**Pull request by RobertoGongora**
## Summary

Fixes #15 — `compact()` never compacts because `ownsCompaction: true` causes the runtime to call `compact()` without `messages`, always falling through to `{ compacted: false }`. Sessions grow unbounded.

- **Set `ownsCompaction: false`** to defer truncation to Pi's built-in auto-compaction
- **Fix `afterTurn` compaction sweep**: when Pi auto-compaction fires mid-prompt, `prePromptMessageCount` becomes stale (pre-compaction count) while `messages` is post-compaction — `slice()` returned `[]`, silently losing the current turn from the graph. Now detects `prePromptMessageCount > messages.length` and sweeps all current messages
- **Add `runtimeContext`/`customInstructions` to `compact()` params** for forward compatibility with a future `compactBuiltIn` callback
- **Bump to v0.6.2**, update CHANGELOG and README provenance table

## Test plan

- [x] All 180 existing + new tests pass (`npm test`)
- [x] Sweep test: `afterTurn` with `prePromptMessageCount: 10, messages: [5 items]` → ingests all 5
- [x] Normal test: `afterTurn` with `prePromptMessageCount: 2, messages: [4 items]` → ingests last 2
- [x] Sweep provenance uses `after_turn_sweep` event
- [x] Normal provenance uses `after_turn` event (no false positive)
- [x] Compact tests unchanged (no logic change, just wider param types)

### CODE REVIEW

File: context-engine.ts [hunk 1]
```diff
@@ -234,6 +234,8 @@ export class GraphitiContextEngine {
     tokenBudget?: number;
     force?: boolean;
     messages?: unknown[];
+    customInstructions?: string;
+    runtimeContext?: Record<string, unknown>;
```
Comment (RobertoGongora) [inline context-engine.ts]: These params are accepted but never referenced in the function body. TypeScript won't flag this (unused object properties aren't caught by `noUnusedParameters`), but a future contributor could trace them expecting to find a call site. A brief comment on the type definition would clarify intent:

```suggestion
    customInstructions?: string; // accepted but unused; reserved for future runtimeContext.compactBuiltIn callback
    runtimeContext?: Record<string, unknown>; // accepted but unused; reserved for future runtimeContext.compactBuiltIn callback
```

File: context-engine.ts [hunk 2]
```diff
@@ -351,7 +353,15 @@ export class GraphitiContextEngine {
...
     }
 
-    const newMessages = params.messages.slice(params.prePromptMessageCount);
+    // When Pi auto-compaction runs during a prompt, prePromptMessageCount
+    // reflects the pre-compaction count while messages is post-compaction.
+    // Detect this mismatch and sweep all messages to avoid losing the
+    // current turn's content from the graph.
+    const compactionOccurred = params.prePromptMessageCount > params.messages.length;
+    const newMessages = compactionOccurred
+      ? params.messages
```
Comment (RobertoGongora) [inline context-engine.ts]: In sweep mode, `params.messages` includes content likely already ingested in a prior `afterTurn` call — the sweep creates a new episode (different timestamp-based name) rather than updating the existing one, so duplicates can occur in the graph. This is intentional (data loss is worse), and the `after_turn_sweep` provenance event already identifies these episodes for filtering. Worth a short inline comment so nobody "fixes" this by changing the behavior:

```suggestion
    // Sweep may re-ingest messages already captured in a prior afterTurn call.
    // Intentional: preventing data loss is more important than deduplication here.
    // Use the "after_turn_sweep" provenance event to identify and filter these.
    const newMessages = compactionOccurred
      ? params.messages
      : params.messages.slice(params.prePromptMessageCount);
```
